### ISSUE TITLE
Logging integration with NLog for .NET Core is not working

### ISSUE THREAD

**Issue by tdmboro** [couchbase/docs-cb4#1750]
Location: https://github.com/couchbase/docs-cb4/blob/master/content/sdk/dotnet/collecting-information-and-logging.dita

NLog has changed since this document was written it appears.

Following the current couchbase instructions for setting up .NET sdk logging in a Core project results in no logs at all (suspect Nlog.Extensions.Logging no longer works with 1.1).  If you dig into their docs, it shows that you need to use Nlog.Web.AspNetCore instead.  Following these setup instructions results in basic logging working, but adding the Couchbase integration still has no discernible effect.  I'm personally new to Couchbase, so hoping there's some guidance available on how to log (it is said to be one of the most effective troubleshooting steps for .NET sdk troubleshooting).

**Comment by MikeGoldsmith** [comment]
Hi @tdmboro 

.NET Core uses Microsoft.Logging instead of NLog because of compatibility issues. There is a section on configuring logging using MS Logging a little further down on the same [page](https://developer.couchbase.com/documentation/server/current/sdk/dotnet/collecting-information-and-logging.html) under section **Logging in applications targeting .NET Core**.

**Comment by tdmboro** [comment]
Hi @MikeGoldsmith 

https://developer.couchbase.com/documentation/server/current/sdk/dotnet/collecting-information-and-logging.html

Perhaps I'm seeing a different version of that page somehow?  The only content under **Logging in applications targeting .NET Core** in the version I can retrieve discusses NLog as the sample, with no specific help links to follow.  Sorry if I sound argumentative, but confused people sometimes have to ask dumb questions...

![capture](https://user-images.githubusercontent.com/30092388/28164304-7fa710de-6794-11e7-8521-33126435aa29.JPG)

**Comment by MikeGoldsmith** [comment]
Hi @tdmboro 

You are correct, I misread your question with regards to the previous logging infrastructure Log4Net for NLog.

I agree and think NLog has changed their implementation targeting .NET Core 1.1. I'll look at getting this working and documentation updated ASAP.

Thanks and sorry for the confusion.

**Comment by MikeGoldsmith** [comment]
@tdmboro 

It seems the new NLog adapter seems to work fine for ASP.NET Core apps. I've put my test project up [here](https://github.com/MikeGoldsmith/CouchbaseCoreLoggingExample).

Log files are going to C:\temp\.

Does that help?

**Comment by MikeGoldsmith** [comment]
Hi @tdmboro - just wanted to let you know I've created this #1789 to update the section with regard to logging in .NET Core applications.

Thanks for reporting the issue.
