### ISSUE TITLE
secure admin acces page not found

### ISSUE THREAD

**Issue by Wingless-Archangel** [couchbase/docs-cb4#1823]
there's a link from Security Best practice from `https://developer.couchbase.com/documentation/server/4.6/security/security-best-practices.`

But, after I tried to visit the link below.

`https://developer.couchbase.com/documentation/server/4.6/security/security-admin-access.html#security-admin-access`

I got the page not found error.

**Comment by mattcarabine** [comment]
Hey @Wingless-Archangel we use JIRA to track our documentation issues. Thanks for reporting this and I've moved it over to https://issues.couchbase.com/browse/DOC-2628 for you!
