### ISSUE TITLE
docs-reorg: Clarification for code examples

### ISSUE THREAD

**Issue by mnunberg** [couchbase/docs-cb4#518]
Code samples typically come in three flavors:
1. One-liners, for example
   
   ```
   cb.upsert(docid, {'key1': 'value1'})
   ```
   
   This kind of example hints at proper usage, but does not entirely reflect what the operation does.
   it is understood that the text surrounding the example provides sufficient explanation
2. Contextual, for example
   
   ```
   rv = cb.upsert(docid, {'key1': 'value1'}
   print rv
   # <OperationResult>...
   ```
   
   This kind of example might provide some additional information at how a specified API or
   operation works, and how it might be used in application code. The example is syntactically
   correct, but may not include all the required components for making it functional.
3. Standalone, for example
   
   ```
   from couchbase.bucket import Bucket
   cb = Bucket('couchbase://localhost/default')
   rv = cb.upsert(docid, {'key1': 'value1'}
   print rv
   # ...
   ```
   
   This is a fully functional, standalone example which can be executed by a user. This may
   contain a significant amount of boilerplate (such as imports and other initialization code)
   needed to make the example standalone.

Examples of the standalone kind will live inside the [devguide-examples](https://github.com/couchbaselabs/devguide-examples) repository. These examples _should_ be copied over to DITA where necessary, but should be modified to be contextual so as not to confuse the reader. A link to the standalone example should be placed near the contextual example, so that a user may be able to further execute and play with the code.

There are no strict rules for where to place examples and what type they should be.

One-liners do not need to be sourced in real code, and are more similar to pseudocode (but are syntactically correct for the language being used).

The content in the devguide-examples repository is versioned by server version (TODO: how to version by SDK version? or perhaps just version that inside the filename?).

Documentation authors (i.e. SDK maintainers) should ensure that in-dita links to the examples refer to the versioned branches, and that fixes in documentation are reflected in both standalone and contextual examples

**Comment by ingenthr** [comment]
This is great.  Probably needs to be in the README or some section of documentation on documentation.

**Comment by amarantha-k** [comment]
Updated readme to include this information (https://github.com/couchbase/docs-cb4/pull/1853)
